name: KramsJams
favicon: null
layout_spectrum: 0.34357
typography_spectrum: 0.38973
title: "Kram's Jams Records"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#555555'
    - '#afafaf'
    - '#000000'
    - '#9f1a1f'
  brandStrength: 0.5625
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
