name: KramsJams
favicon: null
layout_spectrum: 0.60115
typography_spectrum: 0.67382
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: "Kram's Jams Records"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#92D7E7'
    - '#FFFCF6'
    - '#FFF888'
    - '#000000'
    - '#31302F'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
